### PR TITLE
add ccmake per customer request TWC4787-199

### PR DESCRIPTION
**Pull request by jamesreinders**
add ccmake per customer request TWC4787-199
https://jira.devtools.intel.com/projects/TWC4787/issues/TWC4787-199

### CODE REVIEW

**Comment by jamesreinders** [comment]
also add emacs per user request https://jira.devtools.intel.com/projects/TWC4787/issues/TWC4787-205

**Comment by rahulunair** [comment]
Emacs on worker nodes might be an issue, it create a config directory, and as users only have write access to their local env, there might be some errors, also as x11 forwarding is not there, emacs on ubuntu by default expects x11 it will through some warnings. A better alternative would be to install `emacs-nox`

**Comment by jamesreinders** [comment]
Please install an emacs.  I have not had any issues with emacs - I use it on the head node, and on the 1550 systems - so I think you can just use emacs as I proposed with no issue.

However, emacs-nox would be better than nothing - please add one or the other.

**Comment by unrahul** [comment]
Added

**Pull request closed without merging**
